services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    init: true
    ports:
      - "8010:3000"
    environment:
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
      NODE_OPTIONS: --openssl-legacy-provider
      WDS_SOCKET_PORT: 8010
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - default
    command: yarn run start

volumes:
  node_modules:
